name: Build Container Image
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Push-And-Build-Conatiner:
    runs-on: ubuntu-latest
    steps:
     - name: Dev Container Build and Run Action
       # You may pin to the exact commit or the version.
       # uses: devcontainers/ci@72700878095f87b851a6c4405a16056caffdc577
       uses: devcontainers/ci@v0.3.1900000328
       with:
         # Image name (including registry)
         imageName: ghcr.io/afafore1/streamlit-devcontainer
         cacheFrom: ghcr.io/afafore1/streamlit-devcontainer
         push: always
